import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
const alice = '00000000-0000-0000-0000-000000000001', bob = '00000000-0000-0000-0000-000000000002', reviewer = '00000000-0000-0000-0000-000000000003', other = '00000000-0000-0000-0000-000000000004';
test('migration enforces account ownership, permanent records, quotas and reviewer-only resolution', async () => {
 const db = new PGlite();
 await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key,raw_user_meta_data jsonb); create table auth.identities(user_id uuid,provider text); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('app.uid',true),'')::uuid $$; grant usage on schema public,auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;`);
 await db.exec(readFileSync('supabase/migrations/20261008145055_called_it.sql','utf8'));
 for (const id of [alice,bob,reviewer,other]) { await db.query('insert into auth.users values($1,$2)', [id, JSON.stringify({ name: id === alice ? 'Alice' : 'Member' })]); }
 for (const id of [alice,bob,reviewer]) await db.query("insert into auth.identities values($1,'x')",[id]);
 await db.query('insert into called_it_private.reviewers values($1)',[reviewer]);
 const as = async (role: string, id='') => { await db.exec(`reset role; select set_config('app.uid','${id}',false); set role ${role};`); };
 const create = async (author=alice) => db.query<{id:string}>(`insert into public.called_it_predictions(author_id,claim,reasoning,criteria,source_url,deadline) values($1,'We will ship three new pages soon.','An existing foundation makes this achievable.','Count the public routes at the deadline.','https://github.com/sartha555k/ship-a-page',now()+interval '2 days') returning id`,[author]);
 await as('anon'); assert.equal((await db.query('select * from called_it_feed')).rows.length,0); await assert.rejects(()=>create());
 await as('authenticated',other); await assert.rejects(()=>create(other));
 await as('authenticated',alice); await assert.rejects(()=>create(bob)); const {rows:[call]}=await create(); assert.ok(call.id);
 await assert.rejects(()=>db.query("update called_it_predictions set claim='Silently changed my original prediction.' where id=$1",[call.id]));
 assert.equal((await db.query("update called_it_predictions set status='called',resolution_note='A plausible but unauthorized outcome.',evidence_url='https://example.com',resolved_at=now() where id=$1 returning id",[call.id])).rows.length,0);
 await assert.rejects(()=>db.query("delete from called_it_predictions where id=$1",[call.id]));
 await assert.rejects(()=>db.query("insert into called_it_predictions(author_id,claim,reasoning,criteria,source_url,deadline,created_at) values($1,'A valid but backdated call here.','Long enough reasoning for this new call.','A clear measurable outcome at the deadline.','https://example.com',now()+interval '2 days',now()-interval '1 day')",[alice]));
 for(let i=0;i<4;i++) await create(); await assert.rejects(()=>create(),/daily limit/);
 await assert.rejects(()=>db.query("insert into called_it_responses(prediction_id,user_id,stance,argument) values($1,$2,'back','I back my own call here.')",[call.id,alice]),/own call/);
 await as('authenticated',bob);
 await assert.rejects(()=>db.query("insert into called_it_responses(prediction_id,user_id,stance,argument) values($1,$2,'back','An impersonated response here.')",[call.id,alice]));
 await db.query("insert into called_it_responses(prediction_id,user_id,stance,argument) values($1,$2,'challenge','The deadline seems too optimistic.')",[call.id,bob]);
 await assert.rejects(()=>db.query("insert into called_it_responses(prediction_id,user_id,stance,argument) values($1,$2,'back','Changed my recorded response.')",[call.id,bob]));
 await assert.rejects(()=>db.exec("update called_it_responses set argument='Changed the argument after posting.'"));
 await as('authenticated',reviewer); assert.equal((await db.query<{called_it_is_admin:boolean}>('select called_it_is_admin()')).rows[0].called_it_is_admin,true);
 await assert.rejects(()=>db.query("update called_it_predictions set status='called',resolution_note='This outcome is too early to resolve.',evidence_url='https://example.com',resolved_at=now() where id=$1",[call.id]),/not ready/);
 await as('postgres'); await db.exec('alter table called_it_predictions disable trigger called_it_guard_prediction');
 await db.query("update called_it_predictions set created_at=now()-interval '3 days',deadline=now()-interval '1 day' where id=$1",[call.id]);
 await db.exec('alter table called_it_predictions enable trigger called_it_guard_prediction');
 await as('authenticated',bob); await assert.rejects(()=>db.query("insert into called_it_responses(prediction_id,user_id,stance,argument) values($1,$2,'back','Another response after the deadline.')",[call.id,bob]),/closed/);
 await as('authenticated',reviewer); await assert.rejects(()=>db.query("update called_it_predictions set status='called',resolved_at=now() where id=$1",[call.id]));
 await db.query("update called_it_predictions set status='called',resolution_note='The three public pages were present at the deadline.',evidence_url='https://github.com/sartha555k/ship-a-page',resolved_at=now() where id=$1",[call.id]);
 await assert.rejects(()=>db.query("update called_it_predictions set resolution_note='Silently changed the final resolution.' where id=$1",[call.id]),/not ready/);
 await as('anon'); const publicFeed=await db.query<{status:string;challenge_count:number}>('select * from called_it_feed where id=$1',[call.id]); assert.equal(publicFeed.rows[0].status,'called'); assert.equal(Number(publicFeed.rows[0].challenge_count),1);
 await assert.rejects(()=>db.exec('select * from called_it_private.reviewers'));
 await db.close();
});
