import { test } from 'node:test';
import assert from 'node:assert/strict';
import { validateDraft, validateResponse, validateResolution, safeReturn, safeLink } from '../lib/called-it/validation';
const now = Date.parse('2026-10-08T12:00:00Z');
const draft = { claim: 'This project will ship three pages.', reasoning: 'The shared foundation makes this possible.', criteria: 'Count publicly available routes at the deadline.', source_url: 'https://github.com/sartha555k/ship-a-page', deadline: '2026-10-31T12:00:00Z' };
test('valid draft is normalized and constrained', () => { assert.equal(validateDraft({ ...draft, claim: ' '+draft.claim+' ' }, now).claim, draft.claim); assert.throws(() => validateDraft({ ...draft, deadline: '2026-10-08T12:30:00Z' }, now)); assert.throws(() => validateDraft({ ...draft, deadline: '2029-01-01T00:00:00Z' }, now)); assert.throws(() => validateDraft({ ...draft, claim: 'short' }, now)); });
test('URL validation rejects executable and credential-bearing links', () => { for (const url of ['javascript:alert(1)', 'http://example.com', 'https://user:pass@example.com', 'data:text/html,x']) assert.throws(() => safeLink(url)); });
test('OAuth return path cannot redirect off-site', () => { for (const path of ['//evil.example', 'https://evil.example', '/auth/callback', '/experiments/called-it/../../admin']) assert.equal(safeReturn(path), '/experiments/called-it'); assert.equal(safeReturn('/experiments/called-it/1234-5678'), '/experiments/called-it/1234-5678'); });
test('responses and resolutions require valid evidence/arguments', () => { assert.throws(() => validateResponse({ stance: 'back', argument: 'yes' })); assert.throws(() => validateResponse({ stance: 'fake', argument: 'Long enough reasoning' })); assert.throws(() => validateResolution({ status: 'open', resolution_note: 'Long enough reason to resolve.', evidence_url: 'https://example.com' })); assert.equal(validateResponse({ stance: 'challenge', argument: 'I think the deadline is too optimistic.' }).stance, 'challenge'); });
