"use client";
import {useState} from 'react';
import {ArrowRight,ArrowUpRight,Command,Code2,Radar,FlaskConical,Layers3,Menu,X,Check,Zap} from 'lucide-react';
import {BuildCard} from '../components/build-card';
import {SignalBoard} from '../components/signal-board';
import {builds} from '../data/builds';
const portfolio='https://sarthakportfolio-one.vercel.app/';
function Logo(){return <a className="logo" href="#top"><span><Command size={20}/></span>ship<i>/</i>page<b>.</b></a>}
export default function Home(){const [filter,setFilter]=useState('All builds');const [menu,setMenu]=useState(false);const filtered=builds.filter(b=>filter==='All builds'||b.category===filter);return <main id="top">
<header><div className="container nav"><Logo/><nav className={menu?'open':''} aria-label="Main navigation"><a href="#builds" onClick={()=>setMenu(false)}>The builds</a><a href="#approach" onClick={()=>setMenu(false)}>The approach</a><a href={portfolio} target="_blank" rel="noreferrer">Meet the builder <ArrowUpRight size={14}/></a></nav><a href="https://github.com/sartha555k/ship-a-page" className="nav-cta" target="_blank" rel="noreferrer">View on GitHub <ArrowUpRight size={15}/></a><button className="menu" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
<section className="container hero"><div><div className="eyebrow"><span className="dot"/> AN INDEPENDENT BUILD LAB <span className="pill">EST. 2026</span></div><h1>The next thing.<br/>Built into<br/><em>something real.</em></h1><p className="intro">New technology moves fast. We turn the interesting parts into useful, hands-on experiments. One growing playground. Built in public.</p><div className="actions"><a className="button" href="#builds">Explore the builds <ArrowRight size={18}/></a><a className="text-link" href="#approach">How this works <ArrowUpRight size={16}/></a></div><div className="signature"><span>SP</span><div>Built by <a href={portfolio} target="_blank" rel="noreferrer">Sarthak Patel ↗</a><small>Curiosity → code → something you can use.</small></div></div></div><SignalBoard/></section>
<div className="toolkit"><div className="container"><span className="eyebrow">THE TOOLKIT EVOLVES. THE CURIOSITY STAYS.</span><div>Next.js <i>✳</i> React <i>✳</i> TypeScript <i>✳</i> AI + APIs <i>✳</i> Human taste</div></div></div>
<section id="builds" className="container section"><div className="heading"><div><div className="eyebrow">01 / THE BUILD LOG</div><h2>A little less theory.<br/>A lot more <em>trying things.</em></h2></div><p>A living collection of small, focused builds.<br/>Every experiment starts with a good question.</p></div><div className="toolbar"><div className="filters" aria-label="Filter builds">{['All builds','AI + agents','Interfaces','Experiments'].map(f=><button key={f} className={filter===f?'selected':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}{f==='All builds'&&<span>{builds.length}</span>}</button>)}</div><span className="eyebrow"><span className="dot"/> THE LAB IS JUST GETTING STARTED</span></div><div className="build-grid">{filtered.map(build=><BuildCard build={build} key={build.id}/>)}{filtered.length===0?<div className="empty"><FlaskConical size={30}/><h3>Room for the unexpected.</h3><p>No {filter.toLowerCase()} builds yet. The first will appear here once it’s ready to try.</p><button className="text-link" onClick={()=>setFilter('All builds')}>See the foundation <ArrowRight size={16}/></button></div>:<article className="next-build"><div className="next-number">001<span>↗</span></div><div><div className="eyebrow">THE NEXT EXPERIMENT</div><h3>Something worth<br/>opening a new tab for.</h3><p>We’re looking for the next good question.<br/>The first experiment lands here after it’s built.</p></div><div className="next-footer"><span className="eyebrow"><span className="dot"/> ON THE WORKBENCH</span><span>＋</span></div></article>}</div></section>
<section className="approach" id="approach"><div className="container section"><div className="heading"><div><div className="eyebrow">02 / THE APPROACH</div><h2>Good questions.<br/><em>Working answers.</em></h2></div><p>A useful experiment you can actually try,<br/>with a clear idea behind every interaction.</p></div><div className="process">{[{n:'01',title:'Find the signal.',text:'Look beyond the announcement. Explore what people are building, what’s newly possible, and what still feels broken.',Icon:Radar},{n:'02',title:'Ask a better question.',text:'Choose a real problem and an unexpected angle. An experiment earns its place by doing something useful.',Icon:FlaskConical},{n:'03',title:'Make it tangible.',text:'Build a focused interaction. Share what works, explain the tradeoffs, and keep improving the collection.',Icon:Code2}].map(p=><article key={p.n}><div><span>{p.n}</span><p.Icon size={24}/></div><h3>{p.title}</h3><p>{p.text}</p></article>)}</div></div></section>
<section className="container section directions"><div className="eyebrow">03 / AREAS OF CURIOSITY</div>{[{name:'AI + agents',text:'Make intelligence useful. Explore workflows, tool use, and the human side of autonomous systems.',Icon:Zap},{name:'Interfaces',text:'Make complicated things feel simple. Build interactions you can understand by trying them.',Icon:Layers3},{name:'Unexpected ideas',text:'Connect the dots differently. Turn a new capability into something worth playing with.',Icon:FlaskConical}].map((d,i)=><article key={d.name}><span className="eyebrow">0{i+1}</span><d.Icon size={27}/><h3>{d.name}</h3><p>{d.text}</p><ArrowUpRight size={24}/></article>)}</section>
<section className="container closing"><div className="asterisk">✳</div><div className="eyebrow">ALWAYS A WORK IN PROGRESS.</div><h2>Come for the curiosity.<br/><em>Stay for what gets built.</em></h2><a className="button" href="#builds">Back to the workbench <ArrowUpRight size={18}/></a><p>New pages join this collection as experiments become real.</p></section><footer className="container"><Logo/><span>Independent ideas. Shared in public.</span><a href={portfolio} target="_blank" rel="noreferrer">Sarthak Patel ↗</a><a href="#top">Back to top ↑</a></footer>
</main>}
